### ISSUE TITLE
Need to prevent users from making easily breachable passcodes. 

### ISSUE THREAD

**Issue by pogrushan** [Adnan-Jindani/cryptoPlay#20]

**Comment by Adnan-Jindani** [comment]
Yeah! we can do that..

**Comment by PyNonOfReplit** [comment]
I think Wikipedia has a list of most common passwords, we can maybe use that

**Comment by Adnan-Jindani** [comment]
We will just need a set of rules for this..

**Comment by Adnan-Jindani** [comment]
Yeah

**Comment by Adnan-Jindani** [comment]
Development on this project isn't active from now onwards..
