### ISSUE TITLE
Remove calculation lags

### ISSUE THREAD

**Issue by Adnan-Jindani** [Adnan-Jindani/cryptoPlay#25]
This is happening somehow because of flask not refreshing data as database it doing tasks within seconds

**Comment by PyNonOfReplit** [comment]
We may need to change to Django or WSGI serevr

**Comment by Adnan-Jindani** [comment]
The lags were due to WSGI server gunicorn

**Comment by PyNonOfReplit** [comment]
Then we might switch to Django?

**Comment by Adnan-Jindani** [comment]
As of now switching to flask default development server werkzeug
