### ISSUE TITLE
Make the front end responsive for mobile phones

### ISSUE THREAD

**Issue by Adnan-Jindani** [Adnan-Jindani/cryptoPlay#26]

**Comment by PyNonOfReplit** [comment]
Front end responsive for mobile phones? So what exactly do you need changed, I can do this

**Comment by Adnan-Jindani** [comment]
I'll DM you

**Comment by Adnan-Jindani** [comment]
Unassigning as you are woking on another issue right now @PyNonOfReplit

**Comment by ankitrajrj** [comment]
@Adnan-Jindani assign it to me . I want to work on this issue & olz provide me your Twitter or discord I'd for asking questions related to it

**Comment by PyNonOfReplit** [comment]
We also have a discord server for developers and users at  https://discord.gg/GwXqRemN

**Comment by Adnan-Jindani** [comment]
> @Adnan-Jindani assign it to me . I want to work on this issue & olz provide me your Twitter or discord I'd for asking questions related to it

Sure @ankitrajrj Assigning it to you..

**Comment by Adnan-Jindani** [comment]
And @ankitrajrj I am Developer#7300 on discord, you can DM me

**Comment by PyNonOfReplit** [comment]
I'm 3.141592653589793#7068

**Comment by ankitrajrj** [comment]
@Adnan-Jindani this is my discord user id i have sent you request please check:--
Ankit | Contributor#4368

**Comment by Adnan-Jindani** [comment]
> @Adnan-Jindani this is my discord user id i have sent you request please check:-- Ankit | Contributor#4368

Accepted!!..

**Comment by Adnan-Jindani** [comment]
Not needed as of now..
