### ISSUE TITLE
Make the design elegant

### ISSUE THREAD

**Issue by Adnan-Jindani** [Adnan-Jindani/cryptoPlay#38]
@PyNonOfReplit You can handle this one!..

**Comment by PyNonOfReplit** [comment]
Sure, assign it to me

**Comment by Adnan-Jindani** [comment]
Done

**Comment by PyNonOfReplit** [comment]
Cool

**Comment by Adnan-Jindani** [comment]
@PyNonOfReplit Unassigning as you are working on another issue right now

**Comment by Adnan-Jindani** [comment]
Development on this project isn't active from now onwards..
