### ISSUE TITLE
Add forgot password feature

### ISSUE THREAD

**Issue by Adnan-Jindani** [Adnan-Jindani/cryptoPlay#44]

**Comment by shirsho-roy** [comment]
I would like to work on this issue. Could you assign it to me?

**Comment by Adnan-Jindani** [comment]
> I would like to work on this issue. Could you assign it to me?

Sure @shirsho-roy

**Comment by Adnan-Jindani** [comment]
Assigned..

**Comment by Adnan-Jindani** [comment]
@shirsho-roy You there on discord?

**Comment by Adnan-Jindani** [comment]
@shirsho-roy You can DM me on discord. My username is Developer#7300

**Comment by shirsho-roy** [comment]
Did send you a friend request

**Comment by Adnan-Jindani** [comment]
Accepted.. @shirsho-roy

**Comment by Adnan-Jindani** [comment]
Development on this project isn't active from now onwards..
