### ISSUE TITLE
Update Readme.md explaining the setup process

### ISSUE THREAD

**Issue by Adnan-Jindani** [Adnan-Jindani/cryptoPlay#7]

**Comment by PyNonOfReplit** [comment]
I can be doing that

**Comment by Adnan-Jindani** [comment]
> I can be doing that

Okay, I'll assign it to you

**Comment by Adnan-Jindani** [comment]
Unassigning as @PyNonOfReplit is working on another issue as of now..

**Comment by Adnan-Jindani** [comment]
Development on this project isn't active from now onwards..
